// <auto-generated />
using System;
using EFCoreSQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreSQLite.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    [Migration("20180604031805_ModelUpdate")]
    partial class ModelUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("EFCoreSQLite.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("GarageId1");

                    b.Property<Guid?>("GarageId2");

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.HasKey("Id");

                    b.HasIndex("GarageId1");

                    b.HasIndex("GarageId2");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("EFCoreSQLite.Garage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Garages");
                });

            modelBuilder.Entity("EFCoreSQLite.Car", b =>
                {
                    b.HasOne("EFCoreSQLite.Garage", "Garage")
                        .WithMany()
                        .HasForeignKey("GarageId1");

                    b.HasOne("EFCoreSQLite.Garage")
                        .WithMany("Cars")
                        .HasForeignKey("GarageId2");
                });
#pragma warning restore 612, 618
        }
    }
}
